base: &base
  adapter: postgresql
  encoding: utf-8
  pool: 5
  database: development_notification

development:
  <<: *base

test:
  <<: *base
  database: development_notification_test

production:
  <<: *base
